import { adminRoot } from "./config";
import { UserRole } from "../utils/auth.roles";

// id: "dashboards",
// icon: "iconsminds-shop-4",
// label: "menu.dashboards",
// to: `${adminRoot}/dashboards`,
// roles: [UserRole.Admin, UserRole.Editor],

const data = [
  {
    id:"payers",
    icon:"simple-icon-people",
    label: "menu.payers",
    to: `${adminRoot}/dashboard`,
    // roles: [UserRole.Admin, UserRole.Editor],,
    subs:[
      {
      icon: "simple-icon-plus",
      label: "menu.add-payer",
      to: `${adminRoot}/dashboard/add-payer`,
      // roles: [UserRole.Admin, UserRole.Editor],
      },
      {
        icon: "simple-icon-credit-card",
        label: "menu.payer-cards",
        to: `${adminRoot}/dashboard/payers-cards`,
        // roles: [UserRole.Admin, UserRole.Editor],
      },
      {
        icon: "simple-icon-people",
        label: "menu.all-payers",
        to: `${adminRoot}/dashboard/add-payers`,
        // roles: [UserRole.Admin, UserRole.Editor],
      },
    ]
  },
  {id:"agents",
  icon:"simple-icon-people",
  label: "menu.agents",
  to: `${adminRoot}/dashboard/agents`,
  // roles: [UserRole.Admin, UserRole.Editor],,
  subs:[
    {
    icon: "simple-icon-list",
    label: "menu.all-agents",
    to: `${adminRoot}/dashboard/all-agents`,
    // roles: [UserRole.Admin, UserRole.Editor],
    },
    {
      icon: "simple-icon-people",
      label: "menu.port-agents",
      to: `${adminRoot}/dashboard/port-agents`,
      // roles: [UserRole.Admin, UserRole.Editor],
    },
    {
      icon: "simple-icon-people",
      label: "menu.garrage-agents",
      to: `${adminRoot}/dashboard/garrage-agents`,
      // roles: [UserRole.Admin, UserRole.Editor],
    },
    {
      icon: "simple-icon-plus",
      label: "menu.add-agent",
      to: `${adminRoot}/dashboard/add-agent`,
      // roles: [UserRole.Admin, UserRole.Editor],
    },
  ]},
  {id:"admins",
  icon:"simple-icon-graduation",
  label: "menu.admins",
  to: `${adminRoot}/dashboard/admins`,
  // roles: [UserRole.Admin, UserRole.Editor],,
  subs:[
    {
    icon: "simple-icon-list",
    label: "menu.all-admins",
    to: `${adminRoot}/dashboard/all-admins`,
    // roles: [UserRole.Admin, UserRole.Editor],
    },
    {
      icon: "simple-icon-plus",
      label: "menu.add-admin",
      to: `${adminRoot}/dashboard/add-admin`,
      // roles: [UserRole.Admin, UserRole.Editor],
    },
  ]},
  {id:"vehicles",
  icon:"simple-icon-speedometer",
  label: "menu.vehicles",
  to: `${adminRoot}/dashboard/agents`,
  // roles: [UserRole.Admin, UserRole.Editor],,
  subs:[
    {
    icon: "simple-icon-list",
    label: "menu.all-vehicles",
    to: `${adminRoot}/dashboard/all-vehicles`,
    // roles: [UserRole.Admin, UserRole.Editor],
    },
    {
      icon: "simple-icon-list",
      label: "menu.commercial-vehicles",
      to: `${adminRoot}/dashboard/commercial-vehicles`,
      // roles: [UserRole.Admin, UserRole.Editor],
    },
    {
      icon: "simple-icon-list",
      label: "menu.import-vehicles",
      to: `${adminRoot}/dashboard/import-vehicles`,
      // roles: [UserRole.Admin, UserRole.Editor],
    },
    {
      icon: "simple-icon-badge",
      label: "menu.vehicle-tags",
      to: `${adminRoot}/dashboard/vehicle-tags`,
      // roles: [UserRole.Admin, UserRole.Editor],
    },
    {
      icon: "simple-icon-diamond",
      label: "menu.vehicle-payments",
      to: `${adminRoot}/dashboard/vehicle-payments`,
      // roles: [UserRole.Admin, UserRole.Editor],
    },
  ]},
  {id:"cards",
  icon:"simple-icon-credit-card",
  label: "menu.vehicle-cards",
  to: `${adminRoot}/dashboard/cards`,
  // roles: [UserRole.Admin, UserRole.Editor],,
  subs:[
    {
    icon: "simple-icon-list",
    label: "menu.all-cards",
    to: `${adminRoot}/dashboard/all-cards`,
    // roles: [UserRole.Admin, UserRole.Editor],
    },
    {
      icon: "simple-icon-plus",
      label: "menu.add-card",
      to: `${adminRoot}/dashboard/add-card`,
      // roles: [UserRole.Admin, UserRole.Editor],
    },
  ]},
  {id:"vehicle-tags",
  icon:"simple-icon-credit-card",
  label: "menu.vehicle-tags",
  to: `${adminRoot}/dashboard/vehicle-tags`,
  // roles: [UserRole.Admin, UserRole.Editor],,
  subs:[
    {
    icon: "simple-icon-badge",
    label: "menu.all-tags",
    to: `${adminRoot}/dashboard/all-tags`,
    // roles: [UserRole.Admin, UserRole.Editor],
    },
    {
      icon: "simple-icon-plus",
      label: "menu.add-vehicle-tag",
      to: `${adminRoot}/dashboard/add-tag`,
      // roles: [UserRole.Admin, UserRole.Editor],
    },
  ]},
  {id:"finance",
  icon:"simple-icon-credit-card",
  label: "menu.finance",
  to: `${adminRoot}/dashboard/finance`,
  // roles: [UserRole.Admin, UserRole.Editor],,
  subs:[
    {
    icon: "simple-icon-paypal",
    label: "menu.all-vehicle-payments",
    to: `${adminRoot}/dashboard/all-vehicle-payments`,
    // roles: [UserRole.Admin, UserRole.Editor],
    },
    {
      icon: "simple-icon-paypal",
      label: "menu.commercial-vehicle-payments",
      to: `${adminRoot}/dashboard/commercial-vehicle-payments`,
      // roles: [UserRole.Admin, UserRole.Editor],
    },
    {
      icon: "simple-icon-paypal",
      label: "menu.import-vehicle-payments",
      to: `${adminRoot}/dashboard/import-vehicle-payments`,
      // roles: [UserRole.Admin, UserRole.Editor],
    },
  ]},
  {id:"locations",
  icon:"simple-icon-credit-card",
  label: "menu.locations",
  to: `${adminRoot}/dashboard/locations`,
  // roles: [UserRole.Admin, UserRole.Editor],,
  subs:[
    {
    icon: "simple-icon-location-pin",
    label: "menu.local-government",
    to: `${adminRoot}/dashboard/lg`,
    // roles: [UserRole.Admin, UserRole.Editor],
    },
    {
      icon: "simple-icon-plus",
      label: "menu.compass",
      to: `${adminRoot}/dashboard/garrages`,
      // roles: [UserRole.Admin, UserRole.Editor],
    },
  ]},
  { id:"analytics",
    icon: "simple-icon-feed",
    label: "menu.analytics",
    to: `${adminRoot}/dashboard/analytics`,
    // roles: [UserRole.Admin, UserRole.Editor],
  },
  { id:"reports",
    icon: "simple-icon-notebook",
    label: "menu.reports",
    to: `${adminRoot}/dashboard/reports`,
    // roles: [UserRole.Admin, UserRole.Editor],
  },
  {id:"settings",
  icon: "simple-icon-settings",
  label: "menu.settings",
  to: `${adminRoot}/dashboard/settings`,
  // roles: [UserRole.Admin, UserRole.Editor],
  }
];
export default data;
